### ISSUE TITLE
[Player] Create base class

### ISSUE THREAD

**Issue by sanzodown** [yannKiener/Bossfight#1]
- Base actions controllers
      - Interact with
 
- Base movements controllers
 
    
- Basic stats : 
     [] Range
     [] Health
     [] Movespeed

**Comment by yannKiener** [comment]
We now have a class for Characters (and a Player class with controls included) with "classic" stats : Stamina, Force, Intelligence, Agility, Critical, Haste, Power
Sending branch name to QA team.
